### ISSUE TITLE
Runtime issue on Gatsby 2.4.9

### ISSUE THREAD

**Issue by jamaljeantobias** [Jedidiah/gatsby-source-soundcloud#2] opened 2019-04-21 19:44 UTC
Hello 

Came across this run-time error on Gatsby  2.4.9. Any ideas :)
`
error Plugin gatsby-source-soundcloud returned an error
  ReferenceError: regeneratorRuntime is not defined

  - gatsby-node.js:107
    [tone-study]/[gatsby-source-soundcloud]/gatsby-node.js:107:47

  - gatsby-node.js:166 Object.<anonymous>
    [tone-study]/[gatsby-source-soundcloud]/gatsby-node.js:166:2

  - v8-compile-cache.js:178 Module._compile
    [tone-study]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - v8-compile-cache.js:159 require
    [tone-study]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - api-runner-node.js:77 runAPI
    [tone-study]/[gatsby]/dist/utils/api-runner-node.js:77:22

  - api-runner-node.js:258 resolve
    [tone-study]/[gatsby]/dist/utils/api-runner-node.js:258:19

  - debuggability.js:313 Promise._execute
    [tone-study]/[bluebird]/js/release/debuggability.js:313:9

  - promise.js:483 Promise._resolveFromExecutor
    [tone-study]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [tone-study]/[bluebird]/js/release/promise.js:79:10

  - api-runner-node.js:257 Promise.mapSeries.plugin
    [tone-study]/[gatsby]/dist/utils/api-runner-node.js:257:16

  - util.js:16 tryCatcher
    [tone-study]/[bluebird]/js/release/util.js:16:23

  - reduce.js:155 Object.gotValue
    [tone-study]/[bluebird]/js/release/reduce.js:155:18

  - reduce.js:144 Object.gotAccum
    [tone-study]/[bluebird]/js/release/reduce.js:144:25

  - util.js:16 Object.tryCatcher
    [tone-study]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [tone-study]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [tone-study]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [tone-study]/[bluebird]/js/release/promise.js:614:10`

`

**Comment by Jedidiah** [comment] 2019-05-28 00:04
Thank you for reporting. Can reproduce here too, looks like I need to update it, should get to it next week.

**Comment by diegodorado** [comment] 2019-06-04 04:00
Same issue here

**Comment by Jedidiah** [comment] 2019-07-14 23:01
@jamaljeantobias @diegodorado This issue should hopefully now be fixed in 2.0.6 (ae2d7cf127143bc5ef64075a96bc50c7bffd17d8), have updated to Babel v7.
Let me know how you get on.

**Closed by Jedidiah** 2019-07-14 23:01 UTC
